CREATE TABLE `countries` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `printable_name` varchar(100) NOT NULL,
  `iso` varchar(2) NOT NULL,
  `iso3` varchar(3) NOT NULL,
  `num_code` int(11) NOT NULL,
  `dial_code` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=246 ;

--
-- Dumping data for table `countries`
--

INSERT INTO `countries` VALUES(1, 'AFGHANISTAN', 'Afghanistan', 'AF', 'AFG', 4, 93);
INSERT INTO `countries` VALUES(2, 'ALAND ISLANDS', 'Ã…land Islands', 'AX', 'ALA', 248, 0);
INSERT INTO `countries` VALUES(3, 'ALBANIA', 'Albania', 'AL', 'ALB', 8, 355);
INSERT INTO `countries` VALUES(4, 'ALGERIA', 'Algeria', 'DZ', 'DZA', 12, 213);
INSERT INTO `countries` VALUES(5, 'AMERICAN SAMOA', 'American Samoa', 'AS', 'ASM', 16, 1);
INSERT INTO `countries` VALUES(6, 'ANDORRA', 'Andorra', 'AD', 'AND', 20, 376);
INSERT INTO `countries` VALUES(7, 'ANGOLA', 'Angola', 'AO', 'AGO', 24, 244);
INSERT INTO `countries` VALUES(8, 'ANGUILLA', 'Anguilla', 'AI', 'AIA', 660, 1);
INSERT INTO `countries` VALUES(9, 'ANTARCTICA', 'Antarctica', 'AQ', 'ATA', 10, 1);
INSERT INTO `countries` VALUES(10, 'ANTIGUA AND BARBUDA', 'Antigua and Barbuda', 'AG', 'ATG', 28, 1);
INSERT INTO `countries` VALUES(11, 'ARGENTINA', 'Argentina', 'AR', 'ARG', 32, 54);
INSERT INTO `countries` VALUES(12, 'ARMENIA', 'Armenia', 'AM', 'ARM', 51, 374);
INSERT INTO `countries` VALUES(13, 'ARUBA', 'Aruba', 'AW', 'ABW', 533, 0);
INSERT INTO `countries` VALUES(14, 'AUSTRALIA', 'Australia', 'AU', 'AUS', 36, 61);
INSERT INTO `countries` VALUES(15, 'AUSTRIA', 'Austria', 'AT', 'AUT', 40, 43);
INSERT INTO `countries` VALUES(16, 'AZERBAIJAN', 'Azerbaijan', 'AZ', 'AZE', 31, 994);
INSERT INTO `countries` VALUES(17, 'BAHAMAS', 'Bahamas', 'BS', 'BHS', 44, 1);
INSERT INTO `countries` VALUES(18, 'BAHRAIN', 'Bahrain', 'BH', 'BHR', 48, 973);
INSERT INTO `countries` VALUES(19, 'BANGLADESH', 'Bangladesh', 'BD', 'BGD', 50, 880);
INSERT INTO `countries` VALUES(20, 'BARBADOS', 'Barbados', 'BB', 'BRB', 52, 1);
INSERT INTO `countries` VALUES(21, 'BELARUS', 'Belarus', 'BY', 'BLR', 112, 375);
INSERT INTO `countries` VALUES(22, 'BELGIUM', 'Belgium', 'BE', 'BEL', 56, 32);
INSERT INTO `countries` VALUES(23, 'BELIZE', 'Belize', 'BZ', 'BLZ', 84, 501);
INSERT INTO `countries` VALUES(24, 'BENIN', 'Benin', 'BJ', 'BEN', 204, 229);
INSERT INTO `countries` VALUES(25, 'BERMUDA', 'Bermuda', 'BM', 'BMU', 60, 1);
INSERT INTO `countries` VALUES(26, 'BHUTAN', 'Bhutan', 'BT', 'BTN', 64, 975);
INSERT INTO `countries` VALUES(27, 'BOLIVIA', 'Bolivia', 'BO', 'BOL', 68, 591);
INSERT INTO `countries` VALUES(28, 'BOSNIA AND HERZEGOVINA', 'Bosnia and Herzegovina', 'BA', 'BIH', 70, 387);
INSERT INTO `countries` VALUES(29, 'BOTSWANA', 'Botswana', 'BW', 'BWA', 72, 267);
INSERT INTO `countries` VALUES(30, 'BOUVET ISLAND', 'Bouvet Island', 'BV', 'BVT', 74, 0);
INSERT INTO `countries` VALUES(31, 'BRAZIL', 'Brazil', 'BR', 'BRA', 76, 55);
INSERT INTO `countries` VALUES(32, 'BRITISH INDIAN OCEAN TERRITORY', 'British Indian Ocean Territory', 'IO', 'IOT', 86, 0);
INSERT INTO `countries` VALUES(33, 'BRUNEI DARUSSALAM', 'Brunei Darussalam', 'BN', 'BRN', 96, 673);
INSERT INTO `countries` VALUES(34, 'BULGARIA', 'Bulgaria', 'BG', 'BGR', 100, 359);
INSERT INTO `countries` VALUES(35, 'BURKINA FASO', 'Burkina Faso', 'BF', 'BFA', 854, 226);
INSERT INTO `countries` VALUES(36, 'BURUNDI', 'Burundi', 'BI', 'BDI', 108, 257);
INSERT INTO `countries` VALUES(37, 'CAMBODIA', 'Cambodia', 'KH', 'KHM', 116, 855);
INSERT INTO `countries` VALUES(38, 'CAMEROON', 'Cameroon', 'CM', 'CMR', 120, 237);
INSERT INTO `countries` VALUES(39, 'CANADA', 'Canada', 'CA', 'CAN', 124, 1);
INSERT INTO `countries` VALUES(40, 'CAPE VERDE', 'Cape Verde', 'CV', 'CPV', 132, 238);
INSERT INTO `countries` VALUES(41, 'CAYMAN ISLANDS', 'Cayman Islands', 'KY', 'CYM', 136, 1345);
INSERT INTO `countries` VALUES(42, 'CENTRAL AFRICAN REPUBLIC', 'Central African Republic', 'CF', 'CAF', 140, 236);
INSERT INTO `countries` VALUES(43, 'CHAD', 'Chad', 'TD', 'TCD', 148, 235);
INSERT INTO `countries` VALUES(44, 'CHILE', 'Chile', 'CL', 'CHL', 152, 56);
INSERT INTO `countries` VALUES(45, 'CHINA', 'China', 'CN', 'CHN', 156, 86);
INSERT INTO `countries` VALUES(46, 'CHRISTMAS ISLAND', 'Christmas Island', 'CX', 'CXR', 162, 0);
INSERT INTO `countries` VALUES(47, 'COCOS (KEELING) ISLANDS', 'Cocos (Keeling) Islands', 'CC', 'CCK', 166, 0);
INSERT INTO `countries` VALUES(48, 'COLOMBIA', 'Colombia', 'CO', 'COL', 170, 57);
INSERT INTO `countries` VALUES(49, 'COMOROS', 'Comoros', 'KM', 'COM', 174, 269);
INSERT INTO `countries` VALUES(50, 'CONGO', 'Congo', 'CG', 'COG', 178, 242);
INSERT INTO `countries` VALUES(51, 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'Democratic Republic of the Congo', 'CD', 'COD', 180, 243);
INSERT INTO `countries` VALUES(52, 'COOK ISLANDS', 'Cook Islands', 'CK', 'COK', 184, 682);
INSERT INTO `countries` VALUES(53, 'COSTA RICA', 'Costa Rica', 'CR', 'CRI', 188, 506);
INSERT INTO `countries` VALUES(54, 'COTE D''IVOIRE', 'CÃ´te d''Ivoire', 'CI', 'CIV', 384, 225);
INSERT INTO `countries` VALUES(55, 'CROATIA', 'Croatia', 'HR', 'HRV', 191, 385);
INSERT INTO `countries` VALUES(56, 'CUBA', 'Cuba', 'CU', 'CUB', 192, 53);
INSERT INTO `countries` VALUES(57, 'CURACAO', '', 'CW', 'CUW', 0, 599);
INSERT INTO `countries` VALUES(58, 'CYPRUS', 'Cyprus', 'CY', 'CYP', 196, 357);
INSERT INTO `countries` VALUES(59, 'CZECH REPUBLIC', 'Czech Republic', 'CZ', 'CZE', 203, 420);
INSERT INTO `countries` VALUES(60, 'DENMARK', 'Denmark', 'DK', 'DNK', 208, 45);
INSERT INTO `countries` VALUES(61, 'DJIBOUTI', 'Djibouti', 'DJ', 'DJI', 262, 253);
INSERT INTO `countries` VALUES(62, 'DOMINICA', 'Dominica', 'DM', 'DMA', 212, 1);
INSERT INTO `countries` VALUES(63, 'DOMINICAN REPUBLIC', 'Dominican Republic', 'DO', 'DOM', 214, 1);
INSERT INTO `countries` VALUES(64, 'ECUADOR', 'Ecuador', 'EC', 'ECU', 218, 593);
INSERT INTO `countries` VALUES(65, 'EGYPT', 'Egypt', 'EG', 'EGY', 818, 20);
INSERT INTO `countries` VALUES(66, 'EL SALVADOR', 'El Salvador', 'SV', 'SLV', 222, 503);
INSERT INTO `countries` VALUES(67, 'EQUATORIAL GUINEA', 'Equatorial Guinea', 'GQ', 'GNQ', 226, 240);
INSERT INTO `countries` VALUES(68, 'ERITREA', 'Eritrea', 'ER', 'ERI', 232, 291);
INSERT INTO `countries` VALUES(69, 'ESTONIA', 'Estonia', 'EE', 'EST', 233, 372);
INSERT INTO `countries` VALUES(70, 'ETHIOPIA', 'Ethiopia', 'ET', 'ETH', 231, 251);
INSERT INTO `countries` VALUES(71, 'FALKLAND ISLANDS (MALVINAS)', 'Falkland Islands (Malvinas)', 'FK', 'FLK', 238, 0);
INSERT INTO `countries` VALUES(72, 'FAROE ISLANDS', 'Faeroe Islands', 'FO', 'FRO', 234, 0);
INSERT INTO `countries` VALUES(73, 'FIJI', 'Fiji', 'FJ', 'FJI', 242, 679);
INSERT INTO `countries` VALUES(74, 'FINLAND', 'Finland', 'FI', 'FIN', 246, 358);
INSERT INTO `countries` VALUES(75, 'FRANCE', 'France', 'FR', 'FRA', 250, 33);
INSERT INTO `countries` VALUES(76, 'FRENCH GUIANA', 'French Guiana', 'GF', 'GUF', 254, 0);
INSERT INTO `countries` VALUES(77, 'FRENCH POLYNESIA', 'French Polynesia', 'PF', 'PYF', 258, 0);
INSERT INTO `countries` VALUES(78, 'FRENCH SOUTHERN TERRITORIES', 'French Southern Territories', 'TF', 'ATF', 260, 0);
INSERT INTO `countries` VALUES(79, 'GABON', 'Gabon', 'GA', 'GAB', 266, 241);
INSERT INTO `countries` VALUES(80, 'GAMBIA', 'Gambia', 'GM', 'GMB', 270, 220);
INSERT INTO `countries` VALUES(81, 'GEORGIA', 'Georgia', 'GE', 'GEO', 268, 970);
INSERT INTO `countries` VALUES(82, 'GERMANY', 'Germany', 'DE', 'DEU', 276, 49);
INSERT INTO `countries` VALUES(83, 'GHANA', 'Ghana', 'GH', 'GHA', 288, 233);
INSERT INTO `countries` VALUES(84, 'GIBRALTAR', 'Gibraltar', 'GI', 'GIB', 292, 350);
INSERT INTO `countries` VALUES(85, 'GREECE', 'Greece', 'GR', 'GRC', 300, 30);
INSERT INTO `countries` VALUES(86, 'GREENLAND', 'Greenland', 'GL', 'GRL', 304, 299);
INSERT INTO `countries` VALUES(87, 'GRENADA', 'Grenada', 'GD', 'GRD', 308, 1);
INSERT INTO `countries` VALUES(88, 'GUADELOUPE', 'Guadeloupe', 'GP', 'GLP', 312, 590);
INSERT INTO `countries` VALUES(89, 'GUAM', 'Guam', 'GU', 'GUM', 316, 1);
INSERT INTO `countries` VALUES(90, 'GUATEMALA', 'Guatemala', 'GT', 'GTM', 320, 502);
INSERT INTO `countries` VALUES(91, 'GUERNSEY', 'Guernsey', 'GG', 'GGY', 831, 0);
INSERT INTO `countries` VALUES(92, 'GUINEA', 'Guinea', 'GN', 'GIN', 324, 224);
INSERT INTO `countries` VALUES(93, 'GUINEA-BISSAU', 'Guinea-Bissau', 'GW', 'GNB', 624, 245);
INSERT INTO `countries` VALUES(94, 'GUYANA', 'Guyana', 'GY', 'GUY', 328, 592);
INSERT INTO `countries` VALUES(95, 'HAITI', 'Haiti', 'HT', 'HTI', 332, 509);
INSERT INTO `countries` VALUES(96, 'HEARD ISLAND AND MCDONALD ISLANDS', 'Heard Island and Mcdonald Islands', 'HM', 'HMD', 334, 0);
INSERT INTO `countries` VALUES(97, 'HOLY SEE (VATICAN CITY STATE)', 'Holy See (Vatican City State)', 'VA', 'VAT', 336, 379);
INSERT INTO `countries` VALUES(98, 'HONDURAS', 'Honduras', 'HN', 'HND', 340, 504);
INSERT INTO `countries` VALUES(99, 'HONG KONG', 'Hong Kong, SAR', 'HK', 'HKG', 344, 852);
INSERT INTO `countries` VALUES(100, 'HUNGARY', 'Hungary', 'HU', 'HUN', 348, 36);
INSERT INTO `countries` VALUES(101, 'ICELAND', 'Iceland', 'IS', 'ISL', 352, 354);
INSERT INTO `countries` VALUES(102, 'INDIA', 'India', 'IN', 'IND', 356, 91);
INSERT INTO `countries` VALUES(103, 'INDONESIA', 'Indonesia', 'ID', 'IDN', 360, 62);
INSERT INTO `countries` VALUES(104, 'IRAN, ISLAMIC REPUBLIC OF', 'Iran, Islamic Republic of', 'IR', 'IRN', 364, 98);
INSERT INTO `countries` VALUES(105, 'IRAQ', 'Iraq', 'IQ', 'IRQ', 368, 964);
INSERT INTO `countries` VALUES(106, 'IRELAND', 'Ireland', 'IE', 'IRL', 372, 353);
INSERT INTO `countries` VALUES(107, 'ISLE OF MAN', 'Isle of Man', 'IM', 'IMN', 833, 0);
INSERT INTO `countries` VALUES(108, 'ISRAEL', 'Israel', 'IL', 'ISR', 376, 972);
INSERT INTO `countries` VALUES(109, 'ITALY', 'Italy', 'IT', 'ITA', 380, 39);
INSERT INTO `countries` VALUES(110, 'JAMAICA', 'Jamaica', 'JM', 'JAM', 388, 1876);
INSERT INTO `countries` VALUES(111, 'JAPAN', 'Japan', 'JP', 'JPN', 392, 81);
INSERT INTO `countries` VALUES(112, 'JERSEY', 'Jersey', 'JE', 'JEY', 832, 0);
INSERT INTO `countries` VALUES(113, 'JORDAN', 'Jordan', 'JO', 'JOR', 400, 962);
INSERT INTO `countries` VALUES(114, 'KAZAKHSTAN', 'Kazakhstan', 'KZ', 'KAZ', 398, 7);
INSERT INTO `countries` VALUES(115, 'KENYA', 'Kenya', 'KE', 'KEN', 404, 254);
INSERT INTO `countries` VALUES(116, 'KIRIBATI', 'Kiribati', 'KI', 'KIR', 296, 686);
INSERT INTO `countries` VALUES(117, 'KOREA, NORTH', 'Korea, North', 'KP', 'PRK', 408, 850);
INSERT INTO `countries` VALUES(118, 'KOREA, SOUTH', 'Korea, South', 'KR', 'KOR', 410, 82);
INSERT INTO `countries` VALUES(119, 'KUWAIT', 'Kuwait', 'KW', 'KWT', 414, 965);
INSERT INTO `countries` VALUES(120, 'KYRGYZSTAN', 'Kyrgyzstan', 'KG', 'KGZ', 417, 996);
INSERT INTO `countries` VALUES(121, 'LAOS (LAO PR)', 'Laos (Lao PDR)', 'LA', 'LAO', 418, 856);
INSERT INTO `countries` VALUES(122, 'LATVIA', 'Latvia', 'LV', 'LVA', 428, 371);
INSERT INTO `countries` VALUES(123, 'LEBANON', 'Lebanon', 'LB', 'LBN', 422, 961);
INSERT INTO `countries` VALUES(124, 'LESOTHO', 'Lesotho', 'LS', 'LSO', 426, 266);
INSERT INTO `countries` VALUES(125, 'LIBERIA', 'Liberia', 'LR', 'LBR', 430, 231);
INSERT INTO `countries` VALUES(126, 'LIBYAN ARAB JAMAHIRIYA', 'Libyan Arab Jamahiriya (Libya)', 'LY', 'LBY', 434, 218);
INSERT INTO `countries` VALUES(127, 'LIECHTENSTEIN', 'Liechtenstein', 'LI', 'LIE', 438, 423);
INSERT INTO `countries` VALUES(128, 'LITHUANIA', 'Lithuania', 'LT', 'LTU', 440, 370);
INSERT INTO `countries` VALUES(129, 'LUXEMBOURG', 'Luxembourg', 'LU', 'LUX', 442, 352);
INSERT INTO `countries` VALUES(130, 'MACAO', 'Macao (SAR)', 'MO', 'MAC', 446, 853);
INSERT INTO `countries` VALUES(131, 'MACEDONIA', 'Macedonia', 'MK', 'MKD', 807, 389);
INSERT INTO `countries` VALUES(132, 'MADAGASCAR', 'Madagascar', 'MG', 'MDG', 450, 261);
INSERT INTO `countries` VALUES(133, 'MALAWI', 'Malawi', 'MW', 'MWI', 454, 265);
INSERT INTO `countries` VALUES(134, 'MALAYSIA', 'Malaysia', 'MY', 'MYS', 458, 60);
INSERT INTO `countries` VALUES(135, 'MALDIVES', 'Maldives', 'MV', 'MDV', 462, 960);
INSERT INTO `countries` VALUES(136, 'MALI', 'Mali', 'ML', 'MLI', 466, 223);
INSERT INTO `countries` VALUES(137, 'MALTA', 'Malta', 'MT', 'MLT', 470, 356);
INSERT INTO `countries` VALUES(138, 'MARSHALL ISLANDS', 'Marshall Islands', 'MH', 'MHL', 584, 692);
INSERT INTO `countries` VALUES(139, 'MARTINIQUE', 'Martinique', 'MQ', 'MTQ', 474, 596);
INSERT INTO `countries` VALUES(140, 'MAURITANIA', 'Mauritania', 'MR', 'MRT', 478, 222);
INSERT INTO `countries` VALUES(141, 'MAURITIUS', 'Mauritius', 'MU', 'MUS', 480, 230);
INSERT INTO `countries` VALUES(142, 'MAYOTTE', 'Mayotte', 'YT', 'MYT', 175, 262);
INSERT INTO `countries` VALUES(143, 'MEXICO', 'Mexico', 'MX', 'MEX', 484, 52);
INSERT INTO `countries` VALUES(144, 'MICRONESIA, FEDERATED STATES OF', 'Micronesia, Federated States of', 'FM', 'FSM', 583, 691);
INSERT INTO `countries` VALUES(145, 'MOLDOVA, REPUBLIC OF', 'Moldova, Republic of', 'MD', 'MDA', 498, 373);
INSERT INTO `countries` VALUES(146, 'MONACO', 'Monaco', 'MC', 'MCO', 492, 377);
INSERT INTO `countries` VALUES(147, 'MONGOLIA', 'Mongolia', 'MN', 'MNG', 496, 976);
INSERT INTO `countries` VALUES(148, 'MONTENEGRO', 'Montenegro', 'ME', 'MNE', 499, 382);
INSERT INTO `countries` VALUES(149, 'MONTSERRAT', 'Montserrat', 'MS', 'MSR', 500, 1664);
INSERT INTO `countries` VALUES(150, 'MOROCCO', 'Morocco', 'MA', 'MAR', 504, 212);
INSERT INTO `countries` VALUES(151, 'MOZAMBIQUE', 'Mozambique', 'MZ', 'MOZ', 508, 258);
INSERT INTO `countries` VALUES(152, 'MYANMAR', 'Myanmar', 'MM', 'MMR', 104, 95);
INSERT INTO `countries` VALUES(153, 'NAMIBIA', 'Namibia', 'NA', 'NAM', 516, 264);
INSERT INTO `countries` VALUES(154, 'NAURU', 'Nauru', 'NR', 'NRU', 520, 674);
INSERT INTO `countries` VALUES(155, 'NEPAL', 'Nepal', 'NP', 'NPL', 524, 977);
INSERT INTO `countries` VALUES(156, 'NETHERLANDS', 'Netherlands', 'NL', 'NLD', 528, 31);
INSERT INTO `countries` VALUES(157, 'NETHERLANDS ANTILLES', 'Netherlands Antilles', 'AN', 'ANT', 530, 599);
INSERT INTO `countries` VALUES(158, 'NEW CALEDONIA', 'New Caledonia', 'NC', 'NCL', 540, 687);
INSERT INTO `countries` VALUES(159, 'NEW ZEALAND', 'New Zealand', 'NZ', 'NZL', 554, 64);
INSERT INTO `countries` VALUES(160, 'NICARAGUA', 'Nicaragua', 'NI', 'NIC', 558, 505);
INSERT INTO `countries` VALUES(161, 'NIGER', 'Niger', 'NE', 'NER', 562, 227);
INSERT INTO `countries` VALUES(162, 'NIGERIA', 'Nigeria', 'NG', 'NGA', 566, 234);
INSERT INTO `countries` VALUES(163, 'NIUE', 'Niue', 'NU', 'NIU', 570, 683);
INSERT INTO `countries` VALUES(164, 'NORFOLK ISLAND', 'Norfolk Island', 'NF', 'NFK', 574, 672);
INSERT INTO `countries` VALUES(165, 'NORTHERN MARIANA ISLANDS', 'Northern Mariana Islands', 'MP', 'MNP', 580, 1670);
INSERT INTO `countries` VALUES(166, 'NORWAY', 'Norway', 'NO', 'NOR', 578, 47);
INSERT INTO `countries` VALUES(167, 'OMAN', 'Oman', 'OM', 'OMN', 512, 968);
INSERT INTO `countries` VALUES(168, 'PAKISTAN', 'Pakistan', 'PK', 'PAK', 586, 92);
INSERT INTO `countries` VALUES(169, 'PALAU', 'Palau', 'PW', 'PLW', 585, 680);
INSERT INTO `countries` VALUES(170, 'PALESTINIAN TERRITORY, OCCUPIED', 'Palestinian Territory, Occupied', 'PS', 'PSE', 275, 970);
INSERT INTO `countries` VALUES(171, 'PANAMA', 'Panama', 'PA', 'PAN', 591, 507);
INSERT INTO `countries` VALUES(172, 'PAPUA NEW GUINEA', 'Papua New Guinea', 'PG', 'PNG', 598, 675);
INSERT INTO `countries` VALUES(173, 'PARAGUAY', 'Paraguay', 'PY', 'PRY', 600, 595);
INSERT INTO `countries` VALUES(174, 'PERU', 'Peru', 'PE', 'PER', 604, 51);
INSERT INTO `countries` VALUES(175, 'PHILIPPINES', 'Philippines', 'PH', 'PHL', 608, 63);
INSERT INTO `countries` VALUES(176, 'PITCAIRN', 'Pitcairn', 'PN', 'PCN', 612, 870);
INSERT INTO `countries` VALUES(177, 'POLAND', 'Poland', 'PL', 'POL', 616, 48);
INSERT INTO `countries` VALUES(178, 'PORTUGAL', 'Portugal', 'PT', 'PRT', 620, 351);
INSERT INTO `countries` VALUES(179, 'PUERTO RICO', 'Puerto Rico', 'PR', 'PRI', 630, 1);
INSERT INTO `countries` VALUES(180, 'QATAR', 'Qatar', 'QA', 'QAT', 634, 974);
INSERT INTO `countries` VALUES(181, 'REUNION', 'RÃ©union', 'RE', 'REU', 638, 262);
INSERT INTO `countries` VALUES(182, 'ROMANIA', 'Romania', 'RO', 'ROU', 642, 40);
INSERT INTO `countries` VALUES(183, 'RUSSIAN FEDERATION', 'Russia', 'RU', 'RUS', 643, 7);
INSERT INTO `countries` VALUES(184, 'RWANDA', 'Rwanda', 'RW', 'RWA', 646, 250);
INSERT INTO `countries` VALUES(185, 'SAINT HELENA', 'Saint Helena', 'SH', 'SHN', 654, 290);
INSERT INTO `countries` VALUES(186, 'SAINT KITTS AND NEVIS', 'Saint Kitts and Nevis', 'KN', 'KNA', 659, 1);
INSERT INTO `countries` VALUES(187, 'SAINT LUCIA', 'Saint Lucia', 'LC', 'LCA', 662, 1);
INSERT INTO `countries` VALUES(188, 'SAINT PIERRE AND MIQUELON', 'Saint Pierre and Miquelon', 'PM', 'SPM', 666, 508);
INSERT INTO `countries` VALUES(189, 'SAINT VINCENT AND THE GRENADINES', 'Saint Vincent and the Grenadines', 'VC', 'VCT', 670, 1784);
INSERT INTO `countries` VALUES(190, 'SAMOA', 'Samoa', 'WS', 'WSM', 882, 685);
INSERT INTO `countries` VALUES(191, 'SAN MARINO', 'San Marino', 'SM', 'SMR', 674, 378);
INSERT INTO `countries` VALUES(192, 'SAO TOME AND PRINCIPE', 'Sao Tome and Principe', 'ST', 'STP', 678, 239);
INSERT INTO `countries` VALUES(193, 'SAUDI ARABIA', 'Saudi Arabia', 'SA', 'SAU', 682, 966);
INSERT INTO `countries` VALUES(194, 'SENEGAL', 'Senegal', 'SN', 'SEN', 686, 221);
INSERT INTO `countries` VALUES(195, 'SERBIA', 'Serbia', 'RS', 'SRB', 688, 381);
INSERT INTO `countries` VALUES(196, 'SEYCHELLES', 'Seychelles', 'SC', 'SYC', 690, 248);
INSERT INTO `countries` VALUES(197, 'SIERRA LEONE', 'Sierra Leone', 'SL', 'SLE', 694, 232);
INSERT INTO `countries` VALUES(198, 'SINGAPORE', 'Singapore', 'SG', 'SGP', 702, 65);
INSERT INTO `countries` VALUES(199, 'SLOVAKIA', 'Slovakia', 'SK', 'SVK', 703, 421);
INSERT INTO `countries` VALUES(200, 'SLOVENIA', 'Slovenia', 'SI', 'SVN', 705, 386);
INSERT INTO `countries` VALUES(201, 'SOLOMON ISLANDS', 'Solomon Islands', 'SB', 'SLB', 90, 677);
INSERT INTO `countries` VALUES(202, 'SOMALIA', 'Somalia', 'SO', 'SOM', 706, 252);
INSERT INTO `countries` VALUES(203, 'SOUTH AFRICA', 'South Africa', 'ZA', 'ZAF', 710, 27);
INSERT INTO `countries` VALUES(204, 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'South Georgia and the South Sandwich Islands', 'GS', 'SGS', 239, 0);
INSERT INTO `countries` VALUES(205, 'SPAIN', 'Spain', 'ES', 'ESP', 724, 34);
INSERT INTO `countries` VALUES(206, 'SRI LANKA', 'Sri Lanka', 'LK', 'LKA', 144, 94);
INSERT INTO `countries` VALUES(207, 'SUDAN', 'Sudan', 'SD', 'SDN', 736, 249);
INSERT INTO `countries` VALUES(208, 'SURINAME', 'Suriname', 'SR', 'SUR', 740, 597);
INSERT INTO `countries` VALUES(209, 'SVALBARD AND JAN MAYEN', 'Svalbard and Jan Mayen Islands', 'SJ', 'SJM', 744, 47);
INSERT INTO `countries` VALUES(210, 'SWAZILAND', 'Swaziland', 'SZ', 'SWZ', 748, 41);
INSERT INTO `countries` VALUES(211, 'SWEDEN', 'Sweden', 'SE', 'SWE', 752, 46);
INSERT INTO `countries` VALUES(212, 'SWITZERLAND', 'Switzerland', 'CH', 'CHE', 756, 41);
INSERT INTO `countries` VALUES(213, 'SYRIAN ARAB REPUBLIC', 'Syrian Arab Republic', 'SY', 'SYR', 760, 963);
INSERT INTO `countries` VALUES(214, 'TAIWAN, PROVINCE OF CHINA', 'Taiwan, Province of China', 'TW', 'TWN', 158, 886);
INSERT INTO `countries` VALUES(215, 'TAJIKISTAN', 'Tajikistan', 'TJ', 'TJK', 762, 992);
INSERT INTO `countries` VALUES(216, 'TANZANIA, UNITED REPUBLIC OF', 'United Republic of Tanzania', 'TZ', 'TZA', 834, 255);
INSERT INTO `countries` VALUES(217, 'THAILAND', 'Thailand', 'TH', 'THA', 764, 66);
INSERT INTO `countries` VALUES(218, 'TIMOR-LESTE', 'Timor-Leste', 'TL', 'TLS', 626, 670);
INSERT INTO `countries` VALUES(219, 'TOGO', 'Togo', 'TG', 'TGO', 768, 228);
INSERT INTO `countries` VALUES(220, 'TOKELAU', 'Tokelau', 'TK', 'TKL', 772, 690);
INSERT INTO `countries` VALUES(221, 'TONGA', 'Tonga', 'TO', 'TON', 776, 676);
INSERT INTO `countries` VALUES(222, 'TRINIDAD AND TOBAGO', 'Trinidad and Tobago', 'TT', 'TTO', 780, 1);
INSERT INTO `countries` VALUES(223, 'TUNISIA', 'Tunisia', 'TN', 'TUN', 788, 216);
INSERT INTO `countries` VALUES(224, 'TURKEY', 'Turkey', 'TR', 'TUR', 792, 90);
INSERT INTO `countries` VALUES(225, 'TURKMENISTAN', 'Turkmenistan', 'TM', 'TKM', 795, 993);
INSERT INTO `countries` VALUES(226, 'TURKS AND CAICOS ISLANDS', 'Turks and Caicos Islands', 'TC', 'TCA', 796, 1);
INSERT INTO `countries` VALUES(227, 'TUVALU', 'Tuvalu', 'TV', 'TUV', 798, 688);
INSERT INTO `countries` VALUES(228, 'UGANDA', 'Uganda', 'UG', 'UGA', 800, 256);
INSERT INTO `countries` VALUES(229, 'UKRAINE', 'Ukraine', 'UA', 'UKR', 804, 380);
INSERT INTO `countries` VALUES(230, 'UNITED ARAB EMIRATES', 'United Arab Emirates', 'AE', 'ARE', 784, 971);
INSERT INTO `countries` VALUES(231, 'UNITED KINGDOM', 'United Kingdom of Great Britain and Northern Ireland', 'GB', 'GBR', 826, 44);
INSERT INTO `countries` VALUES(232, 'UNITED STATES', 'United States of America', 'US', 'USA', 840, 1);
INSERT INTO `countries` VALUES(233, 'UNITED STATES MINOR OUTLYING ISLANDS', 'United States Minor Outlying Islands', 'UM', 'UMI', 581, 1);
INSERT INTO `countries` VALUES(234, 'URUGUAY', 'Uruguay', 'UY', 'URY', 858, 598);
INSERT INTO `countries` VALUES(235, 'UZBEKISTAN', 'Uzbekistan', 'UZ', 'UZB', 860, 998);
INSERT INTO `countries` VALUES(236, 'VANUATU', 'Vanuatu', 'VU', 'VUT', 548, 678);
INSERT INTO `countries` VALUES(237, 'VENEZUELA', 'Venezuela (Bolivarian Republic of)', 'VE', 'VEN', 862, 58);
INSERT INTO `countries` VALUES(238, 'VIET NAM', 'Viet Nam', 'VN', 'VNM', 704, 84);
INSERT INTO `countries` VALUES(239, 'VIRGIN ISLANDS, BRITISH', 'British Virgin Islands', 'VG', 'VGB', 92, 1);
INSERT INTO `countries` VALUES(240, 'VIRGIN ISLANDS, U.S.', 'United States Virgin Islands', 'VI', 'VIR', 850, 1);
INSERT INTO `countries` VALUES(241, 'WALLIS AND FUTUNA', 'Wallis and Futuna Islands', 'WF', 'WLF', 876, 681);
INSERT INTO `countries` VALUES(242, 'WESTERN SAHARA', 'Western Sahara', 'EH', 'ESH', 732, 212);
INSERT INTO `countries` VALUES(243, 'YEMEN', 'Yemen', 'YE', 'YEM', 887, 967);
INSERT INTO `countries` VALUES(244, 'ZAMBIA', 'Zambia', 'ZM', 'ZMB', 894, 260);
INSERT INTO `countries` VALUES(245, 'ZIMBABWE', 'Zimbabwe', 'ZW', 'ZWE', 716, 263);
